// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: storage.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// get storage data
type GetStorageStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStorageStatsRequest) Reset() {
	*x = GetStorageStatsRequest{}
	mi := &file_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStorageStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStorageStatsRequest) ProtoMessage() {}

func (x *GetStorageStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStorageStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStorageStatsRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{0}
}

func (x *GetStorageStatsRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

type GetStorageStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *StorageStatsProto     `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStorageStatsResponse) Reset() {
	*x = GetStorageStatsResponse{}
	mi := &file_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStorageStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStorageStatsResponse) ProtoMessage() {}

func (x *GetStorageStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStorageStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStorageStatsResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{1}
}

func (x *GetStorageStatsResponse) GetStats() *StorageStatsProto {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *GetStorageStatsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// get storage metadata
type GetStorageMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStorageMetadataRequest) Reset() {
	*x = GetStorageMetadataRequest{}
	mi := &file_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStorageMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStorageMetadataRequest) ProtoMessage() {}

func (x *GetStorageMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStorageMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetStorageMetadataRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{2}
}

func (x *GetStorageMetadataRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

type GetStorageMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *StorageMetadataProto  `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStorageMetadataResponse) Reset() {
	*x = GetStorageMetadataResponse{}
	mi := &file_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStorageMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStorageMetadataResponse) ProtoMessage() {}

func (x *GetStorageMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStorageMetadataResponse.ProtoReflect.Descriptor instead.
func (*GetStorageMetadataResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{3}
}

func (x *GetStorageMetadataResponse) GetMetadata() *StorageMetadataProto {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GetStorageMetadataResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// healthy check
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{4}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{5}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// storage data
type StorageStatsProto struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Timestamp   int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	NodeName    string                 `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	StorageType string                 `protobuf:"bytes,3,opt,name=storage_type,json=storageType,proto3" json:"storage_type,omitempty"` // "lvm", "ceph", "nfs" 等
	// base storage data info
	CapacityBytes  uint64 `protobuf:"varint,4,opt,name=capacity_bytes,json=capacityBytes,proto3" json:"capacity_bytes,omitempty"`
	AvailableBytes uint64 `protobuf:"varint,5,opt,name=available_bytes,json=availableBytes,proto3" json:"available_bytes,omitempty"`
	UsedBytes      uint64 `protobuf:"varint,6,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"`
	// Inode info
	InodesFree uint64 `protobuf:"varint,7,opt,name=inodes_free,json=inodesFree,proto3" json:"inodes_free,omitempty"`
	Inodes     uint64 `protobuf:"varint,8,opt,name=inodes,proto3" json:"inodes,omitempty"`
	InodesUsed uint64 `protobuf:"varint,9,opt,name=inodes_used,json=inodesUsed,proto3" json:"inodes_used,omitempty"`
	// data percent
	DataPercent float64 `protobuf:"fixed64,10,opt,name=data_percent,json=dataPercent,proto3" json:"data_percent,omitempty"`
	// option metrics
	Metrics       map[string]string `protobuf:"bytes,11,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageStatsProto) Reset() {
	*x = StorageStatsProto{}
	mi := &file_storage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageStatsProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageStatsProto) ProtoMessage() {}

func (x *StorageStatsProto) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageStatsProto.ProtoReflect.Descriptor instead.
func (*StorageStatsProto) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{6}
}

func (x *StorageStatsProto) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *StorageStatsProto) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *StorageStatsProto) GetStorageType() string {
	if x != nil {
		return x.StorageType
	}
	return ""
}

func (x *StorageStatsProto) GetCapacityBytes() uint64 {
	if x != nil {
		return x.CapacityBytes
	}
	return 0
}

func (x *StorageStatsProto) GetAvailableBytes() uint64 {
	if x != nil {
		return x.AvailableBytes
	}
	return 0
}

func (x *StorageStatsProto) GetUsedBytes() uint64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

func (x *StorageStatsProto) GetInodesFree() uint64 {
	if x != nil {
		return x.InodesFree
	}
	return 0
}

func (x *StorageStatsProto) GetInodes() uint64 {
	if x != nil {
		return x.Inodes
	}
	return 0
}

func (x *StorageStatsProto) GetInodesUsed() uint64 {
	if x != nil {
		return x.InodesUsed
	}
	return 0
}

func (x *StorageStatsProto) GetDataPercent() float64 {
	if x != nil {
		return x.DataPercent
	}
	return 0
}

func (x *StorageStatsProto) GetMetrics() map[string]string {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// storage metadata
type StorageMetadataProto struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Timestamp   int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	StorageType string                 `protobuf:"bytes,2,opt,name=storage_type,json=storageType,proto3" json:"storage_type,omitempty"` // "lvm", "ceph", "nfs" 等
	NodeName    string                 `protobuf:"bytes,3,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	// base storage metadata info
	MetadataCapacityBytes  uint64  `protobuf:"varint,4,opt,name=metadata_capacity_bytes,json=metadataCapacityBytes,proto3" json:"metadata_capacity_bytes,omitempty"`
	MetadataAvailableBytes uint64  `protobuf:"varint,5,opt,name=metadata_available_bytes,json=metadataAvailableBytes,proto3" json:"metadata_available_bytes,omitempty"`
	MetadataUsedBytes      uint64  `protobuf:"varint,6,opt,name=metadata_used_bytes,json=metadataUsedBytes,proto3" json:"metadata_used_bytes,omitempty"`
	MetadataUsedPercent    float64 `protobuf:"fixed64,7,opt,name=metadata_used_percent,json=metadataUsedPercent,proto3" json:"metadata_used_percent,omitempty"`
	// option metrics
	Metrics       map[string]string `protobuf:"bytes,8,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageMetadataProto) Reset() {
	*x = StorageMetadataProto{}
	mi := &file_storage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageMetadataProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageMetadataProto) ProtoMessage() {}

func (x *StorageMetadataProto) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageMetadataProto.ProtoReflect.Descriptor instead.
func (*StorageMetadataProto) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{7}
}

func (x *StorageMetadataProto) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *StorageMetadataProto) GetStorageType() string {
	if x != nil {
		return x.StorageType
	}
	return ""
}

func (x *StorageMetadataProto) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *StorageMetadataProto) GetMetadataCapacityBytes() uint64 {
	if x != nil {
		return x.MetadataCapacityBytes
	}
	return 0
}

func (x *StorageMetadataProto) GetMetadataAvailableBytes() uint64 {
	if x != nil {
		return x.MetadataAvailableBytes
	}
	return 0
}

func (x *StorageMetadataProto) GetMetadataUsedBytes() uint64 {
	if x != nil {
		return x.MetadataUsedBytes
	}
	return 0
}

func (x *StorageMetadataProto) GetMetadataUsedPercent() float64 {
	if x != nil {
		return x.MetadataUsedPercent
	}
	return 0
}

func (x *StorageMetadataProto) GetMetrics() map[string]string {
	if x != nil {
		return x.Metrics
	}
	return nil
}

var File_storage_proto protoreflect.FileDescriptor

const file_storage_proto_rawDesc = "" +
	"\n" +
	"\rstorage.proto\x12\astorage\"5\n" +
	"\x16GetStorageStatsRequest\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\"a\n" +
	"\x17GetStorageStatsResponse\x120\n" +
	"\x05stats\x18\x01 \x01(\v2\x1a.storage.StorageStatsProtoR\x05stats\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"8\n" +
	"\x19GetStorageMetadataRequest\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\"m\n" +
	"\x1aGetStorageMetadataResponse\x129\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1d.storage.StorageMetadataProtoR\bmetadata\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x14\n" +
	"\x12HealthCheckRequest\"I\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xdc\x03\n" +
	"\x11StorageStatsProto\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x1b\n" +
	"\tnode_name\x18\x02 \x01(\tR\bnodeName\x12!\n" +
	"\fstorage_type\x18\x03 \x01(\tR\vstorageType\x12%\n" +
	"\x0ecapacity_bytes\x18\x04 \x01(\x04R\rcapacityBytes\x12'\n" +
	"\x0favailable_bytes\x18\x05 \x01(\x04R\x0eavailableBytes\x12\x1d\n" +
	"\n" +
	"used_bytes\x18\x06 \x01(\x04R\tusedBytes\x12\x1f\n" +
	"\vinodes_free\x18\a \x01(\x04R\n" +
	"inodesFree\x12\x16\n" +
	"\x06inodes\x18\b \x01(\x04R\x06inodes\x12\x1f\n" +
	"\vinodes_used\x18\t \x01(\x04R\n" +
	"inodesUsed\x12!\n" +
	"\fdata_percent\x18\n" +
	" \x01(\x01R\vdataPercent\x12A\n" +
	"\ametrics\x18\v \x03(\v2'.storage.StorageStatsProto.MetricsEntryR\ametrics\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcc\x03\n" +
	"\x14StorageMetadataProto\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12!\n" +
	"\fstorage_type\x18\x02 \x01(\tR\vstorageType\x12\x1b\n" +
	"\tnode_name\x18\x03 \x01(\tR\bnodeName\x126\n" +
	"\x17metadata_capacity_bytes\x18\x04 \x01(\x04R\x15metadataCapacityBytes\x128\n" +
	"\x18metadata_available_bytes\x18\x05 \x01(\x04R\x16metadataAvailableBytes\x12.\n" +
	"\x13metadata_used_bytes\x18\x06 \x01(\x04R\x11metadataUsedBytes\x122\n" +
	"\x15metadata_used_percent\x18\a \x01(\x01R\x13metadataUsedPercent\x12D\n" +
	"\ametrics\x18\b \x03(\v2*.storage.StorageMetadataProto.MetricsEntryR\ametrics\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\x8f\x02\n" +
	"\x0eStorageService\x12T\n" +
	"\x0fGetStorageStats\x12\x1f.storage.GetStorageStatsRequest\x1a .storage.GetStorageStatsResponse\x12]\n" +
	"\x12GetStorageMetadata\x12\".storage.GetStorageMetadataRequest\x1a#.storage.GetStorageMetadataResponse\x12H\n" +
	"\vHealthCheck\x12\x1b.storage.HealthCheckRequest\x1a\x1c.storage.HealthCheckResponseBBZ@github.com/labring/sealos/controllers/devbox/internal/stat/protob\x06proto3"

var (
	file_storage_proto_rawDescOnce sync.Once
	file_storage_proto_rawDescData []byte
)

func file_storage_proto_rawDescGZIP() []byte {
	file_storage_proto_rawDescOnce.Do(func() {
		file_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storage_proto_rawDesc), len(file_storage_proto_rawDesc)))
	})
	return file_storage_proto_rawDescData
}

var file_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_storage_proto_goTypes = []any{
	(*GetStorageStatsRequest)(nil),     // 0: storage.GetStorageStatsRequest
	(*GetStorageStatsResponse)(nil),    // 1: storage.GetStorageStatsResponse
	(*GetStorageMetadataRequest)(nil),  // 2: storage.GetStorageMetadataRequest
	(*GetStorageMetadataResponse)(nil), // 3: storage.GetStorageMetadataResponse
	(*HealthCheckRequest)(nil),         // 4: storage.HealthCheckRequest
	(*HealthCheckResponse)(nil),        // 5: storage.HealthCheckResponse
	(*StorageStatsProto)(nil),          // 6: storage.StorageStatsProto
	(*StorageMetadataProto)(nil),       // 7: storage.StorageMetadataProto
	nil,                                // 8: storage.StorageStatsProto.MetricsEntry
	nil,                                // 9: storage.StorageMetadataProto.MetricsEntry
}
var file_storage_proto_depIdxs = []int32{
	6, // 0: storage.GetStorageStatsResponse.stats:type_name -> storage.StorageStatsProto
	7, // 1: storage.GetStorageMetadataResponse.metadata:type_name -> storage.StorageMetadataProto
	8, // 2: storage.StorageStatsProto.metrics:type_name -> storage.StorageStatsProto.MetricsEntry
	9, // 3: storage.StorageMetadataProto.metrics:type_name -> storage.StorageMetadataProto.MetricsEntry
	0, // 4: storage.StorageService.GetStorageStats:input_type -> storage.GetStorageStatsRequest
	2, // 5: storage.StorageService.GetStorageMetadata:input_type -> storage.GetStorageMetadataRequest
	4, // 6: storage.StorageService.HealthCheck:input_type -> storage.HealthCheckRequest
	1, // 7: storage.StorageService.GetStorageStats:output_type -> storage.GetStorageStatsResponse
	3, // 8: storage.StorageService.GetStorageMetadata:output_type -> storage.GetStorageMetadataResponse
	5, // 9: storage.StorageService.HealthCheck:output_type -> storage.HealthCheckResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_storage_proto_init() }
func file_storage_proto_init() {
	if File_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storage_proto_rawDesc), len(file_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_storage_proto_goTypes,
		DependencyIndexes: file_storage_proto_depIdxs,
		MessageInfos:      file_storage_proto_msgTypes,
	}.Build()
	File_storage_proto = out.File
	file_storage_proto_goTypes = nil
	file_storage_proto_depIdxs = nil
}
