apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/name: devbox
    control-plane: controller-manager
  name: devbox-controller-manager
  namespace: devbox-system
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --metrics-bind-address=:8443
        - --health-probe-bind-address=:8081
        - --registry-addr=sealos.hub:5000
        - --registry-user=admin
        - --registry-password=passw0rd
        - --restart-predicate-duration=1000000h
        command:
        - /manager
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: crpi-5yq5lj8mtkm1w8pm.cn-hangzhou.personal.cr.aliyuncs.com/linzichun-namespace/devbox-controller:v2.7
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 1
        name: manager
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 1500m
            memory: 2000Mi
          requests:
            cpu: 100m
            memory: 640Mi
        securityContext:
          privileged: true
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /run/containerd
          name: containerd-run-dir
        - mountPath: /var/run/containerd
          name: containerd-var-run-dir
        - mountPath: /var/lib/containerd
          mountPropagation: Bidirectional
          name: containerd-dir
        - mountPath: /etc/containerd/certs.d
          name: hosts-dir
        - mountPath: /tmp
          name: tmp-dir
      - args:
        - --grpc-port=9090
        - --storage-type=lvm
        - --monitor-interval=5s
        - --enable-grpc=true
        - --enable-monitoring=true
        command:
        - /app/storage-server
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: crpi-5yq5lj8mtkm1w8pm.cn-hangzhou.personal.cr.aliyuncs.com/linzichun-namespace/storage-server:v2.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - grpc-health-probe
            - -addr=localhost:9090
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 5
        name: storage-server
        ports:
        - containerPort: 9090
          name: grpc
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - grpc-health-probe
            - -addr=localhost:9090
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: true
          privileged: true
          runAsGroup: 0
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /dev
          name: device-dir
      dnsPolicy: ClusterFirst
      nodeSelector:
        devbox.sealos.io/node: ""
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsUser: 0
      serviceAccount: devbox-controller-manager
      serviceAccountName: devbox-controller-manager
      terminationGracePeriodSeconds: 10
      volumes:
      - hostPath:
          path: /run/containerd
          type: Directory
        name: containerd-run-dir
      - hostPath:
          path: /var/run/containerd
          type: Directory
        name: containerd-var-run-dir
      - hostPath:
          path: /var/lib/containerd
          type: Directory
        name: containerd-dir
      - hostPath:
          path: /etc/containerd/certs.d
          type: Directory
        name: hosts-dir
      - hostPath:
          path: /tmp
          type: Directory
        name: tmp-dir
      - hostPath:
          path: /dev
          type: Directory
        name: device-dir
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
